In [1]:
import numpy as np

def qr_iteration(A, iterations=10):
    """
    Melakukan iterasi QR pada matriks A sebanyak n kali.
    """
    Ak = A.copy()

    print(f"Matriks Awal:\n{Ak}\n")
    print("-" * 30)

    for i in range(1, iterations + 1):
        # Langkah 1: Dekomposisi QR
        Q, R = np.linalg.qr(Ak)

        # Langkah 2: Hitung matriks berikutnya (Ak+1 = R * Q)
        Ak = np.dot(R, Q)

        print(f"Iterasi ke-{i}:")
        print(Ak)
        print("-" * 30)

    return Ak

# Contoh penggunaan:
# Mendefinisikan matriks persegi (n x n)
A = np.array([[4, 1, -1],
              [1, 2, 1],
              [-1, 1, 3]], dtype=float)

# Menjalankan fungsi
final_matrix = qr_iteration(A, 10)

print("\nHasil Akhir (Nilai Eigen mendekati elemen diagonal):")
print(np.diag(final_matrix))

Matriks Awal:
[[ 4.  1. -1.]
 [ 1.  2.  1.]
 [-1.  1.  3.]]

------------------------------
Iterasi ke-1:
[[ 4.61111111 -0.11586227  0.33633189]
 [-0.11586227  3.29250335 -0.84909609]
 [ 0.33633189 -0.84909609  1.09638554]]
------------------------------
Iterasi ke-2:
[[ 4.64935065 -0.1632803  -0.06026051]
 [-0.1632803   3.54948434  0.20279363]
 [-0.06026051  0.20279363  0.80116501]]
------------------------------
Iterasi ke-3:
[[ 4.66054716 -0.12766028  0.01020242]
 [-0.12766028  3.55304944 -0.04419888]
 [ 0.01020242 -0.04419888  0.7864034 ]]
------------------------------
Iterasi ke-4:
[[ 4.66673659e+00 -9.72797594e-02 -1.71949575e-03]
 [-9.72797594e-02  3.54754875e+00  9.67835192e-03]
 [-1.71949575e-03  9.67835192e-03  7.85714662e-01]]
------------------------------
Iterasi ke-5:
[[ 4.67030527e+00 -7.38801280e-02  2.89428862e-04]
 [-7.38801280e-02  3.54401282e+00 -2.13119568e-03]
 [ 2.89428862e-04 -2.13119568e-03  7.85681917e-01]]
------------------------------
Iterasi ke-6:
[[ 4.67